version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
    ignore:
      # requires Redis 4+
      - dependency-name: sidekiq
        versions:
        - ">= 6.0.0"
      # incompatible with hackney_template
      - dependency-name: sass-rails
        versions:
        - ">= 6.0.0"
