AllCops:
  Exclude:
    - 'Vagrantfile'
    - 'db/migrate/**'
    - 'db/schema.rb'
    - 'gems/**/*'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/DotPosition:
  EnforcedStyle: trailing

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
