---
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'Vagrantfile'
    - 'bin/bundle'
    - 'config/rails_env.rb'
    - 'db/migrate/**'
    - 'db/schema.rb'
    - 'gems/**/*'
    - 'lib/mysociety/validate.rb'
    - 'vendor/**/*'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/factories/*.rb'
    - 'spec/**/*_spec.rb'
    - 'config/routes.rb'

Layout/LineLength:
  Max: 80
  IgnoredPatterns:
    - '^\s*it\s+.*do$'
    - '^\s*context\s+.*do$'
    - '^\s*describe\s+.*do$'

Layout/DotPosition:
  EnforcedStyle: trailing

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
