language: ruby
services:
  - redis-server
addons:
  postgresql: "9.6"
rvm: 2.5.8
cache: bundler
sudo: false
before_script:
  - psql -c 'create database foi_for_councils_test;' -U postgres
  - cp config/database.yml-travis config/database.yml
before_install:
  - "echo '--colour' > ~/.rspec"
install: bundle install
notifications:
  email: false
