name: CI

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile || 'Gemfile' }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
        - { ruby: 2.6 }
        - { ruby: 2.7 }
        - { ruby: 2.7, gemfile: 'gemfiles/rails_main.gemfile' }

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile || 'Gemfile' }}
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/alaveteli_test
      REDIS_URL: redis://localhost:6379/0
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Setup database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Setup configuration
      run: cp config/case_management.yml-example config/case_management.yml

    - name: Run tests
      run: |
        bundle exec rspec
