name: RuboCop

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Run RuboCop linter
      uses: reviewdog/action-rubocop@v1
      with:
        github_token: ${{ secrets.github_token }}
        rubocop_version: 1.10.0
        rubocop_extensions: rubocop-performance:1.9.2 rubocop-rails:2.9.1
