name: RuboCop

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: rubocop
    steps:
    - uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - run: |
        gem install securerandom -v 0.3.2
        gem install activesupport -v 7.1.5.1

    - name: Run RuboCop linter
      uses: reviewdog/action-rubocop@v2
      with:
        github_token: ${{ secrets.github_token }}
        rubocop_version: gemfile
        rubocop_extensions: rubocop-performance:gemfile rubocop-rails:gemfile
        level: warning
